### ISSUE TITLE
Issue Encountered During Checkpoint Smart Contract Deployment

### ISSUE THREAD

**Issue by vrushalipanchal** [XinFinOrg/XDC-Subnet#97]
Hello @wanwiset25,

On my system Subnet Relayer status was "Abnormal", to address this, I pulled the latest Subnet Generator Image and followed further process.

During the deployment of the checkpoint smart contract, I encountered the following error:

Error:
Error: Fetch remote subnet node data error , pls check the subnet node status
    at Object.data (/app/contract/scripts/utils/subnet.js:33:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at main (/app/contract/scripts/FullCheckpointDeploy.js:5:42)
    .
    . 
    CSC deployment failed

![image](https://github.com/XinFinOrg/XDC-Subnet/assets/39384359/3627e718-ba3e-421c-9024-58ade7e05bac)

This has resulted in the failure of the CSC deployment process. I would appreciate your assistance in resolving this issue.

Thank you.

**Comment by wanwiset25** [comment]
Hi @vrushalipanchal 

This is due to your subnet status during the deployment.

There are 2 things
1. The subnet status. Is it live and mining blocks?
2. Your connectivity to the subnet. Are you deploying CSC on the same machine as the subnet? If not, is the subnet node's IP/port reachable and not firewalled?

What is the output when trying the below. You can also try replacing  'localhost' with subnet machine's IP
```
curl --location 'localhost:8545' \
--header 'Content-Type: application/json' \
--data '{"jsonrpc":"2.0","method":"XDPoS_getV2BlockByNumber","params":["0x0"],"id":1}'
```


Additionally, these are the relevant configs. It is sensitive to post here so you can share on telegram or my email: wanwiset@xinfin.org

deployment.config.json
common.env

**Comment by wanwiset25** [comment]
Hi @vrushalipanchal 

It is hard to say without full visibility of the system. But I suspect that some parts are not running correctly. To troubleshoot, we need to confirm from the ground up.  This is the description at a high level:

Bootnode is running > Subnets successful peering > Subnets mining > CSC deployed > Relayer pushing > Backend is up > Front end is up

The confirmation can be done by checking docker logs or curl the RPC. Some basic troubleshooting instructions can be found here https://xinfinorg.github.io/xdc-subnet-docs/deployment/debug_guide

**Comment by vrushalipanchal** [comment]
@wanwiset25 Noted. I will check the Debug guide
