### ISSUE TITLE
Query regarding the application of the latest changes to the Subnet

### ISSUE THREAD

**Issue by vrushalipanchal** [XinFinOrg/XDC-Subnet#98]
Hello Team,

I have a query regarding the application of the latest changes to the Subnet. If someone wants to apply the latest changes to their Subnet, could you please provide the specific commands that need to be executed for this purpose? 

Additionally, I would recommend implementing a single command, such as "bash upgrade.sh," which would streamline the process of applying all the latest changes and starting the service.

Your assistance on this matter would be greatly appreciated.

Thank you.

**Comment by wanwiset25** [comment]
Hi @vrushalipanchal 

Thank you for your suggestion. We will look to add this in the next version and document it. 

Meanwhile, if version changes is required, you can check each service's image tag inside "docker-compose.yml".
Once modified use the 'pull' command (ex. "docker compose --env-file docker-compose.env --profile machine1 pull") to update the image. Then, deploy with the 'up' command (ex. " docker compose --env-file docker-compose.env --profile machine1 up -d")

To check the available image tags, you can visit https://hub.docker.com/u/xinfinorg

When generating Subnet configs, the latest stable image tags are used by default. You can also check this file for the stable versions https://github.com/XinFinOrg/XinFin-Node/blob/master/subnet/deployment-generator/script/gen_config.js

**Comment by wanwiset25** [comment]
After consideration I think upgrading the subnet is done rarely and making an "upgrade.sh" script feels over engineered. The problem is that we shouldn't use "latest" tag so upgrade.sh has to know what versions to upgrade to.  I can think of 2 ways to do this.
1. maintain a versions file inside the repo or on-cloud where upgrade.sh reads from
2. put the versions info inside upgrade.sh and the user has to pull the new script on every update

Both methods has associated overhead as compared to simply upgrading through editing "docker-compose.yml" file.
I've included the upgrade instructions to the documentation https://xinfinorg.github.io/xdc-subnet-docs/deployment/upgrading_the_subnet
